// generated by diplomat-tool
import type { BidiParagraph } from "./BidiParagraph"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** An object containing bidi information for a given string, produced by `for_text()` on `Bidi`
*
*See the [Rust documentation for `BidiInfo`](https://docs.rs/unicode_bidi/latest/unicode_bidi/struct.BidiInfo.html) for more information.
*/
export class BidiInfo {
    

    get ffiValue(): pointer;


    get paragraphCount(): number;

    paragraphAt(n: number): BidiParagraph | undefined;

    get size(): number;

    levelAt(pos: number): number;

    

}