// generated by diplomat-tool
import type { BidiDirection } from "./BidiDirection"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** Bidi information for a single processed paragraph
*/
export class BidiParagraph {
    

    get ffiValue(): pointer;


    setParagraphInText(n: number): boolean;

    get direction(): BidiDirection;

    get size(): number;

    get rangeStart(): number;

    get rangeEnd(): number;

    reorderLine(rangeStart: number, rangeEnd: number): string | undefined;

    levelAt(pos: number): number;

    

}