// generated by diplomat-tool
import type { AnyCalendarKind } from "./AnyCalendarKind"
import type { DataProvider } from "./DataProvider"
import type { Locale } from "./Locale"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** See the [Rust documentation for `AnyCalendar`](https://docs.rs/icu/latest/icu/calendar/enum.AnyCalendar.html) for more information.
*/
export class Calendar {
    

    get ffiValue(): pointer;


    static createForLocale(provider: DataProvider, locale: Locale): Calendar;

    static createForKind(provider: DataProvider, kind: AnyCalendarKind): Calendar;

    get kind(): AnyCalendarKind;

    

}