// generated by diplomat-tool
import type { DataProvider } from "./DataProvider"
import type { Decomposed } from "./Decomposed"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** The raw (non-recursive) canonical decomposition operation.
*
*Callers should generally use DecomposingNormalizer unless they specifically need raw composition operations
*
*See the [Rust documentation for `CanonicalDecomposition`](https://docs.rs/icu/latest/icu/normalizer/properties/struct.CanonicalDecomposition.html) for more information.
*/
export class CanonicalDecomposition {
    

    get ffiValue(): pointer;


    static create(provider: DataProvider): CanonicalDecomposition;

    decompose(c: char): Decomposed;

    

}