// generated by diplomat-tool
import type { DataProvider } from "./DataProvider"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** The raw canonical composition operation.
*
*Callers should generally use ComposingNormalizer unless they specifically need raw composition operations
*
*See the [Rust documentation for `CanonicalComposition`](https://docs.rs/icu/latest/icu/normalizer/properties/struct.CanonicalComposition.html) for more information.
*/
export class CanonicalComposition {
    

    get ffiValue(): pointer;


    static create(provider: DataProvider): CanonicalComposition;

    compose(starter: char, second: char): char;

    

}