// generated by diplomat-tool
import type { CodePointSetBuilder } from "./CodePointSetBuilder"
import type { DataProvider } from "./DataProvider"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** See the [Rust documentation for `CaseMapCloser`](https://docs.rs/icu/latest/icu/casemap/struct.CaseMapCloser.html) for more information.
*/
export class CaseMapCloser {
    

    get ffiValue(): pointer;


    static create(provider: DataProvider): CaseMapCloser;

    addCaseClosureTo(c: char, builder: CodePointSetBuilder): void;

    addStringCaseClosureTo(s: string, builder: CodePointSetBuilder): boolean;

    

}