// generated by diplomat-tool
import type { CodePointRangeIteratorResult } from "./CodePointRangeIteratorResult"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** An iterator over code point ranges, produced by `CodePointSetData` or
*one of the `CodePointMapData` types
*/
export class CodePointRangeIterator {
    

    get ffiValue(): pointer;


    next(): CodePointRangeIteratorResult;

    

}