// generated by diplomat-tool
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";

// Base enumerator definition
/** See the [Rust documentation for `MaxVariable`](https://docs.rs/icu/latest/icu/collator/enum.MaxVariable.html) for more information.
*/
export class CollatorMaxVariable {
    constructor(value : CollatorMaxVariable | string);

    get value() : string;

    get ffiValue() : number;

    static Auto : CollatorMaxVariable;

    static Space : CollatorMaxVariable;

    static Punctuation : CollatorMaxVariable;

    static Symbol : CollatorMaxVariable;

    static Currency : CollatorMaxVariable;


    

}