// generated by diplomat-tool
import type { CollatorOptions } from "./CollatorOptions"
import type { DataProvider } from "./DataProvider"
import type { Locale } from "./Locale"
import type { ResolvedCollatorOptions } from "./ResolvedCollatorOptions"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** See the [Rust documentation for `Collator`](https://docs.rs/icu/latest/icu/collator/struct.Collator.html) for more information.
*/
export class Collator {
    

    get ffiValue(): pointer;


    static create(provider: DataProvider, locale: Locale, options: CollatorOptions): Collator;

    compare(left: string, right: string): number;

    get resolvedOptions(): ResolvedCollatorOptions;

    

}