// generated by diplomat-tool
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";

// Base enumerator definition
/** See the [Rust documentation for `CaseFirst`](https://docs.rs/icu/latest/icu/collator/enum.CaseFirst.html) for more information.
*/
export class CollatorCaseFirst {
    constructor(value : CollatorCaseFirst | string);

    get value() : string;

    get ffiValue() : number;

    static Auto : CollatorCaseFirst;

    static Off : CollatorCaseFirst;

    static LowerFirst : CollatorCaseFirst;

    static UpperFirst : CollatorCaseFirst;


    

}