// generated by diplomat-tool
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";

// Base enumerator definition
/** See the [Rust documentation for `Date`](https://docs.rs/icu/latest/icu/datetime/options/length/enum.Date.html) for more information.
*/
export class DateLength {
    constructor(value : DateLength | string);

    get value() : string;

    get ffiValue() : number;

    static Full : DateLength;

    static Long : DateLength;

    static Medium : DateLength;

    static Short : DateLength;


    

}