// generated by diplomat-tool
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";

// Base enumerator definition
/** See the [Rust documentation for `Fallback`](https://docs.rs/icu/latest/icu/displaynames/options/enum.Fallback.html) for more information.
*/
export class DisplayNamesFallback {
    constructor(value : DisplayNamesFallback | string);

    get value() : string;

    get ffiValue() : number;

    static Code : DisplayNamesFallback;

    static None : DisplayNamesFallback;


    

}