// generated by diplomat-tool
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";

// Base enumerator definition
/** The sign of a FixedDecimal, as shown in formatting.
*
*See the [Rust documentation for `Sign`](https://docs.rs/fixed_decimal/latest/fixed_decimal/enum.Sign.html) for more information.
*/
export class FixedDecimalSign {
    constructor(value : FixedDecimalSign | string);

    get value() : string;

    get ffiValue() : number;

    static None : FixedDecimalSign;

    static Negative : FixedDecimalSign;

    static Positive : FixedDecimalSign;


    

}