// generated by diplomat-tool
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";

// Base enumerator definition
/** Mode used in a rounding operation.
*
*See the [Rust documentation for `RoundingMode`](https://docs.rs/fixed_decimal/latest/fixed_decimal/enum.RoundingMode.html) for more information.
*/
export class FixedDecimalRoundingMode {
    constructor(value : FixedDecimalRoundingMode | string);

    get value() : string;

    get ffiValue() : number;

    static Ceil : FixedDecimalRoundingMode;

    static Expand : FixedDecimalRoundingMode;

    static Floor : FixedDecimalRoundingMode;

    static Trunc : FixedDecimalRoundingMode;

    static HalfCeil : FixedDecimalRoundingMode;

    static HalfExpand : FixedDecimalRoundingMode;

    static HalfFloor : FixedDecimalRoundingMode;

    static HalfTrunc : FixedDecimalRoundingMode;

    static HalfEven : FixedDecimalRoundingMode;


    

}