// generated by diplomat-tool
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";

// Base enumerator definition
/** Increment used in a rounding operation.
*
*See the [Rust documentation for `RoundingIncrement`](https://docs.rs/fixed_decimal/latest/fixed_decimal/enum.RoundingIncrement.html) for more information.
*/
export class FixedDecimalRoundingIncrement {
    constructor(value : FixedDecimalRoundingIncrement | string);

    get value() : string;

    get ffiValue() : number;

    static MultiplesOf1 : FixedDecimalRoundingIncrement;

    static MultiplesOf2 : FixedDecimalRoundingIncrement;

    static MultiplesOf5 : FixedDecimalRoundingIncrement;

    static MultiplesOf25 : FixedDecimalRoundingIncrement;


    

}