// generated by diplomat-tool
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";

// Base enumerator definition
/** Additional information: [1](https://docs.rs/fixed_decimal/latest/fixed_decimal/struct.LimitError.html)
*/
export class FixedDecimalLimitError {
    constructor(value : FixedDecimalLimitError | string);

    get value() : string;

    get ffiValue() : number;

    static TodoZst : FixedDecimalLimitError;


    

}