// generated by diplomat-tool
import type { DataProvider } from "./DataProvider"
import type { GraphemeClusterBreakIteratorUtf16 } from "./GraphemeClusterBreakIteratorUtf16"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** An ICU4X grapheme-cluster-break segmenter, capable of finding grapheme cluster breakpoints
*in strings.
*
*See the [Rust documentation for `GraphemeClusterSegmenter`](https://docs.rs/icu/latest/icu/segmenter/struct.GraphemeClusterSegmenter.html) for more information.
*/
export class GraphemeClusterSegmenter {
    

    get ffiValue(): pointer;


    static create(provider: DataProvider): GraphemeClusterSegmenter;

    segment(input: string): GraphemeClusterBreakIteratorUtf16;

    

}