// generated by diplomat-tool
import type { DataProvider } from "./DataProvider"
import type { DateLength } from "./DateLength"
import type { IsoDateTime } from "./IsoDateTime"
import type { Locale } from "./Locale"
import type { TimeLength } from "./TimeLength"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** An ICU4X TypedDateTimeFormatter object capable of formatting a [`IsoDateTime`] as a string,
*using the Gregorian Calendar.
*
*See the [Rust documentation for `TypedDateTimeFormatter`](https://docs.rs/icu/latest/icu/datetime/struct.TypedDateTimeFormatter.html) for more information.
*/
export class GregorianDateTimeFormatter {
    

    get ffiValue(): pointer;


    static createWithLengths(provider: DataProvider, locale: Locale, dateLength: DateLength, timeLength: TimeLength): GregorianDateTimeFormatter;

    formatIsoDatetime(value: IsoDateTime): string;

    

}