// generated by diplomat-tool
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";

// Base enumerator definition
/** See the [Rust documentation for `IsoMinutes`](https://docs.rs/icu/latest/icu/datetime/time_zone/enum.IsoMinutes.html) for more information.
*/
export class IsoTimeZoneMinuteDisplay {
    constructor(value : IsoTimeZoneMinuteDisplay | string);

    get value() : string;

    get ffiValue() : number;

    static Required : IsoTimeZoneMinuteDisplay;

    static Optional : IsoTimeZoneMinuteDisplay;


    

}