// generated by diplomat-tool
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";

// Base enumerator definition
/** See the [Rust documentation for `IsoSeconds`](https://docs.rs/icu/latest/icu/datetime/time_zone/enum.IsoSeconds.html) for more information.
*/
export class IsoTimeZoneSecondDisplay {
    constructor(value : IsoTimeZoneSecondDisplay | string);

    get value() : string;

    get ffiValue() : number;

    static Optional : IsoTimeZoneSecondDisplay;

    static Never : IsoTimeZoneSecondDisplay;


    

}