// generated by diplomat-tool
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";

// Base enumerator definition
/** See the [Rust documentation for `LineBreakWordOption`](https://docs.rs/icu/latest/icu/segmenter/enum.LineBreakWordOption.html) for more information.
*/
export class LineBreakWordOption {
    constructor(value : LineBreakWordOption | string);

    get value() : string;

    get ffiValue() : number;

    static Normal : LineBreakWordOption;

    static BreakAll : LineBreakWordOption;

    static KeepAll : LineBreakWordOption;


    

}