// generated by diplomat-tool
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";

// Base enumerator definition
/** See the [Rust documentation for `LineBreakStrictness`](https://docs.rs/icu/latest/icu/segmenter/enum.LineBreakStrictness.html) for more information.
*/
export class LineBreakStrictness {
    constructor(value : LineBreakStrictness | string);

    get value() : string;

    get ffiValue() : number;

    static Loose : LineBreakStrictness;

    static Normal : LineBreakStrictness;

    static Strict : LineBreakStrictness;

    static Anywhere : LineBreakStrictness;


    

}