// generated by diplomat-tool
import type { LineBreakStrictness } from "./LineBreakStrictness"
import type { LineBreakWordOption } from "./LineBreakWordOption"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** See the [Rust documentation for `LineBreakOptions`](https://docs.rs/icu/latest/icu/segmenter/struct.LineBreakOptions.html) for more information.
*/
export class LineBreakOptions {
    #strictness;
    get strictness() : LineBreakStrictness;
    set strictness(value: LineBreakStrictness); 
    #wordOption;
    get wordOption() : LineBreakWordOption;
    set wordOption(value: LineBreakWordOption); 
    #jaZh;
    get jaZh() : boolean;
    set jaZh(value: boolean); 

    

}