// generated by diplomat-tool
import type { DataProvider } from "./DataProvider"
import type { DisplayNamesOptions } from "./DisplayNamesOptions"
import type { Locale } from "./Locale"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** See the [Rust documentation for `LocaleDisplayNamesFormatter`](https://docs.rs/icu/latest/icu/displaynames/struct.LocaleDisplayNamesFormatter.html) for more information.
*/
export class LocaleDisplayNamesFormatter {
    

    get ffiValue(): pointer;


    static create(provider: DataProvider, locale: Locale, options: DisplayNamesOptions): LocaleDisplayNamesFormatter;

    of(locale: Locale): string;

    

}