// generated by diplomat-tool
import type { DataProvider } from "./DataProvider"
import type { LocaleFallbackConfig } from "./LocaleFallbackConfig"
import type { LocaleFallbackerWithConfig } from "./LocaleFallbackerWithConfig"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** An object that runs the ICU4X locale fallback algorithm.
*
*See the [Rust documentation for `LocaleFallbacker`](https://docs.rs/icu/latest/icu/locale/fallback/struct.LocaleFallbacker.html) for more information.
*/
export class LocaleFallbacker {
    

    get ffiValue(): pointer;


    static create(provider: DataProvider): LocaleFallbacker;

    static createWithoutData(): LocaleFallbacker;

    forConfig(config: LocaleFallbackConfig): LocaleFallbackerWithConfig;

    

}