// generated by diplomat-tool
import type { DataProvider } from "./DataProvider"
import type { Locale } from "./Locale"
import type { LocaleDirection } from "./LocaleDirection"
import type { LocaleExpander } from "./LocaleExpander"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** See the [Rust documentation for `LocaleDirectionality`](https://docs.rs/icu/latest/icu/locale/struct.LocaleDirectionality.html) for more information.
*/
export class LocaleDirectionality {
    

    get ffiValue(): pointer;


    static create(provider: DataProvider): LocaleDirectionality;

    static createWithExpander(provider: DataProvider, expander: LocaleExpander): LocaleDirectionality;

    get(locale: Locale): LocaleDirection;

    isLeftToRight(locale: Locale): boolean;

    isRightToLeft(locale: Locale): boolean;

    

}