// generated by diplomat-tool
import type { DataProvider } from "./DataProvider"
import type { Locale } from "./Locale"
import type { TransformResult } from "./TransformResult"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** A locale canonicalizer.
*
*See the [Rust documentation for `LocaleCanonicalizer`](https://docs.rs/icu/latest/icu/locale/struct.LocaleCanonicalizer.html) for more information.
*/
export class LocaleCanonicalizer {
    

    get ffiValue(): pointer;


    static create(provider: DataProvider): LocaleCanonicalizer;

    static createExtended(provider: DataProvider): LocaleCanonicalizer;

    canonicalize(locale: Locale): TransformResult;

    

}