// generated by diplomat-tool
import type { Locale } from "./Locale"
import type { LocaleFallbackIterator } from "./LocaleFallbackIterator"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** An object that runs the ICU4X locale fallback algorithm with specific configurations.
*
*See the [Rust documentation for `LocaleFallbacker`](https://docs.rs/icu/latest/icu/locale/fallback/struct.LocaleFallbacker.html) for more information.
*
*See the [Rust documentation for `LocaleFallbackerWithConfig`](https://docs.rs/icu/latest/icu/locale/fallback/struct.LocaleFallbackerWithConfig.html) for more information.
*/
export class LocaleFallbackerWithConfig {
    

    get ffiValue(): pointer;


    fallbackForLocale(locale: Locale): LocaleFallbackIterator;

    

}