// generated by diplomat-tool
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** An ICU4X Locale, capable of representing strings like `"en-US"`.
*
*See the [Rust documentation for `Locale`](https://docs.rs/icu/latest/icu/locale/struct.Locale.html) for more information.
*/
export class Locale {
    

    get ffiValue(): pointer;


    static createFromString(name: string): Locale;

    static createUnd(): Locale;

    clone(): Locale;

    get basename(): string;

    getUnicodeExtension(s: string): string | undefined;

    get language(): string;

    set language(s: string): void;

    get region(): string | undefined;

    set region(s: string): void;

    get script(): string | undefined;

    set script(s: string): void;

    static canonicalize(s: string): string;

    toString(): string;

    normalizingEq(other: string): boolean;

    compareToString(other: string): number;

    compareTo(other: Locale): number;

    

}