// generated by diplomat-tool
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";

// Base enumerator definition
/** Priority mode for the ICU4X fallback algorithm.
*
*See the [Rust documentation for `LocaleFallbackPriority`](https://docs.rs/icu/latest/icu/locale/fallback/enum.LocaleFallbackPriority.html) for more information.
*/
export class LocaleFallbackPriority {
    constructor(value : LocaleFallbackPriority | string);

    get value() : string;

    get ffiValue() : number;

    static Language : LocaleFallbackPriority;

    static Region : LocaleFallbackPriority;

    static Collation : LocaleFallbackPriority;


    

}