// generated by diplomat-tool
import type { LocaleFallbackPriority } from "./LocaleFallbackPriority"
import type { LocaleFallbackSupplement } from "./LocaleFallbackSupplement"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** Collection of configurations for the ICU4X fallback algorithm.
*
*See the [Rust documentation for `LocaleFallbackConfig`](https://docs.rs/icu/latest/icu/locale/fallback/struct.LocaleFallbackConfig.html) for more information.
*/
export class LocaleFallbackConfig {
    #priority;
    get priority() : LocaleFallbackPriority;
    set priority(value: LocaleFallbackPriority); 
    #extensionKey;
    get extensionKey() : string;
    set extensionKey(value: string); 
    #fallbackSupplement;
    get fallbackSupplement() : LocaleFallbackSupplement;
    set fallbackSupplement(value: LocaleFallbackSupplement); 

    

}