// generated by diplomat-tool
import type { DataProvider } from "./DataProvider"
import type { Locale } from "./Locale"
import type { TransformResult } from "./TransformResult"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** A locale expander.
*
*See the [Rust documentation for `LocaleExpander`](https://docs.rs/icu/latest/icu/locale/struct.LocaleExpander.html) for more information.
*/
export class LocaleExpander {
    

    get ffiValue(): pointer;


    static create(provider: DataProvider): LocaleExpander;

    static createExtended(provider: DataProvider): LocaleExpander;

    maximize(locale: Locale): TransformResult;

    minimize(locale: Locale): TransformResult;

    minimizeFavorScript(locale: Locale): TransformResult;

    

}