// generated by diplomat-tool
import type { Locale } from "./Locale"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** An iterator over the locale under fallback.
*
*See the [Rust documentation for `LocaleFallbackIterator`](https://docs.rs/icu/latest/icu/locale/fallback/struct.LocaleFallbackIterator.html) for more information.
*/
export class LocaleFallbackIterator {
    

    get ffiValue(): pointer;


    next(): Locale | undefined;

    

}