// generated by diplomat-tool
import type { MeasureUnit } from "./MeasureUnit"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** An ICU4X Measurement Unit parser object which is capable of parsing the CLDR unit identifier
*(e.g. `meter-per-square-second`) and get the [`MeasureUnit`].
*
*See the [Rust documentation for `MeasureUnitParser`](https://docs.rs/icu/latest/icu/experimental/units/measureunit/struct.MeasureUnitParser.html) for more information.
*/
export class MeasureUnitParser {
    

    get ffiValue(): pointer;


    parse(unitId: string): MeasureUnit | undefined;

    

}