// generated by diplomat-tool
import type { DataProvider } from "./DataProvider"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** An object capable of computing the metazone from a timezone.
*
*This can be used via `maybe_calculate_metazone()` on [`CustomTimeZone`].
*
*[`CustomTimeZone`]: crate::timezone::ffi::CustomTimeZone
*
*See the [Rust documentation for `MetazoneCalculator`](https://docs.rs/icu/latest/icu/timezone/struct.MetazoneCalculator.html) for more information.
*/
export class MetazoneCalculator {
    

    get ffiValue(): pointer;


    static create(provider: DataProvider): MetazoneCalculator;

    

}