// generated by diplomat-tool
import type { FixedDecimal } from "./FixedDecimal"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** See the [Rust documentation for `PluralOperands`](https://docs.rs/icu/latest/icu/plurals/struct.PluralOperands.html) for more information.
*/
export class PluralOperands {
    

    get ffiValue(): pointer;


    static createFromString(s: string): PluralOperands;

    static createFromFixedDecimal(x: FixedDecimal): PluralOperands;

    

}