// generated by diplomat-tool
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";

// Base enumerator definition
/** See the [Rust documentation for `PluralCategory`](https://docs.rs/icu/latest/icu/plurals/enum.PluralCategory.html) for more information.
*/
export class PluralCategory {
    constructor(value : PluralCategory | string);

    get value() : string;

    get ffiValue() : number;

    static Zero : PluralCategory;

    static One : PluralCategory;

    static Two : PluralCategory;

    static Few : PluralCategory;

    static Many : PluralCategory;

    static Other : PluralCategory;


    static getForCldrString(s: string): PluralCategory | undefined;

    

}