// generated by diplomat-tool
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";

export class PluralCategories {
    #zero;
    get zero() : boolean;
    
    #one;
    get one() : boolean;
    
    #two;
    get two() : boolean;
    
    #few;
    get few() : boolean;
    
    #many;
    get many() : boolean;
    
    #other;
    get other() : boolean;
    

    

}