// generated by diplomat-tool
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** Thin wrapper around a vector that maps visual indices to source indices
*
*`map[visualIndex] = sourceIndex`
*
*Produced by `reorder_visual()` on [`Bidi`].
*/
export class ReorderedIndexMap {
    

    get ffiValue(): pointer;


    get asSlice(): Array<number>;

    get length(): number;

    get isEmpty(): boolean;

    get(index: number): number;

    

}