// generated by diplomat-tool
import type { CodePointSetData } from "./CodePointSetData"
import type { ScriptExtensionsSet } from "./ScriptExtensionsSet"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** A slightly faster ScriptWithExtensions object
*
*See the [Rust documentation for `ScriptWithExtensionsBorrowed`](https://docs.rs/icu/latest/icu/properties/script/struct.ScriptWithExtensionsBorrowed.html) for more information.
*/
export class ScriptWithExtensionsBorrowed {
    

    get ffiValue(): pointer;


    getScriptVal(codePoint: number): number;

    getScriptExtensionsVal(codePoint: number): ScriptExtensionsSet;

    hasScript(codePoint: number, script: number): boolean;

    getScriptExtensionsSet(script: number): CodePointSetData;

    

}