// generated by diplomat-tool
import type { CodePointRangeIterator } from "./CodePointRangeIterator"
import type { DataProvider } from "./DataProvider"
import type { ScriptWithExtensionsBorrowed } from "./ScriptWithExtensionsBorrowed"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** An ICU4X ScriptWithExtensions map object, capable of holding a map of codepoints to scriptextensions values
*
*See the [Rust documentation for `ScriptWithExtensions`](https://docs.rs/icu/latest/icu/properties/script/struct.ScriptWithExtensions.html) for more information.
*/
export class ScriptWithExtensions {
    

    get ffiValue(): pointer;


    static create(provider: DataProvider): ScriptWithExtensions;

    getScriptVal(codePoint: number): number;

    hasScript(codePoint: number, script: number): boolean;

    get asBorrowed(): ScriptWithExtensionsBorrowed;

    iterRangesForScript(script: number): CodePointRangeIterator;

    

}