// generated by diplomat-tool
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** An object that represents the Script_Extensions property for a single character
*
*See the [Rust documentation for `ScriptExtensionsSet`](https://docs.rs/icu/latest/icu/properties/script/struct.ScriptExtensionsSet.html) for more information.
*/
export class ScriptExtensionsSet {
    

    get ffiValue(): pointer;


    contains(script: number): boolean;

    get count(): number;

    scriptAt(index: number): number | undefined;

    

}