// generated by diplomat-tool
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";

// Base enumerator definition
/** See the [Rust documentation for `WordType`](https://docs.rs/icu/latest/icu/segmenter/enum.WordType.html) for more information.
*/
export class SegmenterWordType {
    constructor(value : SegmenterWordType | string);

    get value() : string;

    get ffiValue() : number;

    static None : SegmenterWordType;

    static Number : SegmenterWordType;

    static Letter : SegmenterWordType;


    get isWordLike(): boolean;

    

}