// generated by diplomat-tool
import type { DataProvider } from "./DataProvider"
import type { SentenceBreakIteratorUtf16 } from "./SentenceBreakIteratorUtf16"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** An ICU4X sentence-break segmenter, capable of finding sentence breakpoints in strings.
*
*See the [Rust documentation for `SentenceSegmenter`](https://docs.rs/icu/latest/icu/segmenter/struct.SentenceSegmenter.html) for more information.
*/
export class SentenceSegmenter {
    

    get ffiValue(): pointer;


    static create(provider: DataProvider): SentenceSegmenter;

    segment(input: string): SentenceBreakIteratorUtf16;

    

}