// generated by diplomat-tool
import type { DataProvider } from "./DataProvider"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** A mapper between IANA time zone identifiers and BCP-47 time zone identifiers.
*
*This mapper supports two-way mapping, but it is optimized for the case of IANA to BCP-47.
*It also supports normalizing and canonicalizing the IANA strings.
*
*See the [Rust documentation for `TimeZoneIdMapperWithFastCanonicalization`](https://docs.rs/icu/latest/icu/timezone/struct.TimeZoneIdMapperWithFastCanonicalization.html) for more information.
*/
export class TimeZoneIdMapperWithFastCanonicalization {
    

    get ffiValue(): pointer;


    static create(provider: DataProvider): TimeZoneIdMapperWithFastCanonicalization;

    canonicalizeIana(value: string): string;

    canonicalIanaFromBcp47(value: string): string;

    

}