// generated by diplomat-tool
import type { LeadingAdjustment } from "./LeadingAdjustment"
import type { TrailingCase } from "./TrailingCase"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** See the [Rust documentation for `TitlecaseOptions`](https://docs.rs/icu/latest/icu/casemap/titlecase/struct.TitlecaseOptions.html) for more information.
*/
export class TitlecaseOptions {
    #leadingAdjustment;
    get leadingAdjustment() : LeadingAdjustment;
    set leadingAdjustment(value: LeadingAdjustment); 
    #trailingCase;
    get trailingCase() : TrailingCase;
    set trailingCase(value: TrailingCase); 

    static defaultOptions(): TitlecaseOptions;

    

}