// generated by diplomat-tool
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";

// Base enumerator definition
/** See the [Rust documentation for `TransformResult`](https://docs.rs/icu/latest/icu/locale/enum.TransformResult.html) for more information.
*/
export class TransformResult {
    constructor(value : TransformResult | string);

    get value() : string;

    get ffiValue() : number;

    static Modified : TransformResult;

    static Unmodified : TransformResult;


    

}