// generated by diplomat-tool
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** An ICU4X Units Converter object, capable of converting between two [`MeasureUnit`]s.
*
*You can create an instance of this object using [`UnitsConverterFactory`] by calling the `converter` method.
*
*See the [Rust documentation for `UnitsConverter`](https://docs.rs/icu/latest/icu/experimental/units/converter/struct.UnitsConverter.html) for more information.
*/
export class UnitsConverter {
    

    get ffiValue(): pointer;


    convert(value: number): number;

    clone(): UnitsConverter;

    

}