// generated by diplomat-tool
import type { DataProvider } from "./DataProvider"
import type { MeasureUnit } from "./MeasureUnit"
import type { MeasureUnitParser } from "./MeasureUnitParser"
import type { UnitsConverter } from "./UnitsConverter"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** An ICU4X Units Converter Factory object, capable of creating converters a [`UnitsConverter`]
*for converting between two [`MeasureUnit`]s.
*Also, it can parse the CLDR unit identifier (e.g. `meter-per-square-second`) and get the [`MeasureUnit`].
*
*See the [Rust documentation for `ConverterFactory`](https://docs.rs/icu/latest/icu/experimental/units/converter_factory/struct.ConverterFactory.html) for more information.
*/
export class UnitsConverterFactory {
    

    get ffiValue(): pointer;


    static create(provider: DataProvider): UnitsConverterFactory;

    converter(from: MeasureUnit, to: MeasureUnit): UnitsConverter | undefined;

    parser(): MeasureUnitParser;

    

}