// generated by diplomat-tool
import type { WeekRelativeUnit } from "./WeekRelativeUnit"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** See the [Rust documentation for `WeekOf`](https://docs.rs/icu/latest/icu/calendar/week/struct.WeekOf.html) for more information.
*/
export class WeekOf {
    #week;
    get week() : number;
    
    #unit;
    get unit() : WeekRelativeUnit;
    

    

}