// generated by diplomat-tool
import type { SegmenterWordType } from "./SegmenterWordType"
import type { u8, i8, u16, i16, u32, i32, u64, i64, usize, isize, f32, f64, pointer, char } from "./diplomat-runtime.d.ts";


/** See the [Rust documentation for `WordBreakIterator`](https://docs.rs/icu/latest/icu/segmenter/struct.WordBreakIterator.html) for more information.
*/
export class WordBreakIteratorLatin1 {
    

    get ffiValue(): pointer;


    next(): number;

    get wordType(): SegmenterWordType;

    get isWordLike(): boolean;

    

}